services:
  beszel:
    container_name: beszel
    image: henrygd/beszel:0.19.0@sha256:fefb27166f5e1611ebf67f8697ea928a23f44efdb00af922e2ac3b5faa2efd5c
    restart: unless-stopped
    ports:
      - 127.0.0.1:8090:8090
    volumes:
      - beszel_data:/beszel_data
      - beszel_socket:/beszel_socket
    environment:
      - APP_URL=http://localhost:8090

  beszel-agent:
    container_name: beszel-agent
    image: henrygd/beszel-agent:0.19.0@sha256:00c88600e7d120128f623b2deb5257603d464e841fd68f88cc791dcc075f9e46
    restart: unless-stopped
    volumes:
      - beszel_socket:/beszel_socket
      - var_lib_beszel_agent:/var/lib/beszel-agent
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - HUB_URL=http://beszel:8090
      - KEY=${KEY}
      - LISTEN=/beszel_socket/beszel.sock
      - TOKEN=${TOKEN}
    depends_on:
      - beszel

volumes:
  beszel_data:
  beszel_socket:
  var_lib_beszel_agent:
