services:
  navidrome:
    container_name: navidrome
    image: deluan/navidrome:0.63.2
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - data:/data
      - /srv/navidrome/music:/music
      - ./data/navidrome.toml:/data/navidrome.toml
    env_file:
      - .env

networks:
  proxy:
    external: true

volumes:
  data:
