services:
  navidrome:
    container_name: navidrome
    image: deluan/navidrome:0.63.2
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - ND_LASTFM_APIKEY=${ND_LASTFM_APIKEY}
      - ND_LASTFM_SECRET=${ND_LASTFM_SECRET}
    volumes:
      - data:/data
      - /srv/navidrome/music:/music
      - ./data/navidrome.toml:/data/navidrome.toml

networks:
  proxy:
    external: true

volumes:
  data:
