x-logging: &default-logging
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: 3

services:
  beszel:
    <<: *default-logging
    container_name: beszel
    image: henrygd/beszel:0.19.0
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - ./beszel_data:/beszel_data
      - ./beszel_socket:/beszel_socket
    environment:
      - USER_EMAIl=${BESZEL_USER_EMAIL}
      - USER_PASSWORD=${BESZEL_USER_PASSWORD}

  beszel-agent:
    <<: *default-logging
    container_name: beszel-agent
    image: henrygd/beszel-agent:0.19.0
    restart: unless-stopped
    volumes:
      - ./beszel_socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - HUB_URL=http://beszel:8090
      - KEY=${BESZEL_KEY}
      - TOKEN=${BESZEL_TOKEN}

  caddy:
    <<: *default-logging
    container_name: caddy
    image: caddy:2.11.4
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./caddy_data:/data
      - ./caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
    extra_hosts:
      - host.docker.internal:host-gateway

  livekit-server:
    <<: *default-logging
    container_name: livekit-server
    image: livekit/livekit-server:v1.13.6
    restart: unless-stopped
    environment:
      - 'LIVEKIT_CONFIG={"rtc":{"udp_port":7882}}'
      - "LIVEKIT_KEYS=${LIVEKIT_KEY}: ${LIVEKIT_SECRET}"
      - LIVEKIT_NODE=${LIVEKIT_NODE}
    network_mode: host

  lk-jwt-service:
    <<: *default-logging
    container_name: lk-jwt-service
    image: ghcr.io/element-hq/lk-jwt-service:0.7.0
    restart: unless-stopped
    environment:
      - LIVEKIT_FULL_ACCESS_HOMESERVERS=${LIVEKIT_FULL_ACCESS_HOMESERVERS}
      - LIVEKIT_KEY=${LIVEKIT_KEY}
      - LIVEKIT_SECRET=${LIVEKIT_SECRET}
      - LIVEKIT_URL=${LIVEKIT_URL}

  tuwunel:
    <<: *default-logging
    container_name: tuwunel
    image: ghcr.io/matrix-construct/tuwunel:v1.9.0
    restart: unless-stopped
    environment:
      - TUWUNEL_ADDRESS=0.0.0.0
      - TUWUNEL_ALLOW_REGISTRATION=${TUWUNEL_ALLOW_REGISTRATION}
      - TUWUNEL_REGISTRATION_TOKEN=${TUWUNEL_REGISTRATION_TOKEN}
      - TUWUNEL_SERVER_NAME=${TUWUNEL_SERVER_NAME}
    volumes:
      - ./var_lib_tuwunel:/var/lib/tuwunel
