services:
  coturn:
    container_name: "coturn"
    image: coturn/coturn:4.18.0
    restart: unless-stopped
    command:
      - turnserver
      - -n
      - --use-auth-secret
      - --static-auth-secret=${STATIC_AUTH_SECRET}
      - --realm=matrix.ocd.beauty
      - --external-ip=${EXTERNAL_IP}
    network_mode: host
