services:
  tuwunel:
    container_name: tuwunel
    image: ghcr.io/matrix-construct/tuwunel:v1.9.0@sha256:295a1ceedbfd7afce05c69a38efb246dd31fa810e5d352fc7a09b261853800ee
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - TUWUNEL_ADDRESS=0.0.0.0
      - TUWUNEL_ALLOW_REGISTRATION=true
      - TUWUNEL_REGISTRATION_TOKEN=${TUWUNEL_REGISTRATION_TOKEN}
      - TUWUNEL_SERVER_NAME=matrix.ocd.beauty
    volumes:
      - var_lib_tuwunel:/var/lib/tuwunel

networks:
  proxy:
    external: true

volumes:
  var_lib_tuwunel:
