services:
  losi-online:
    container_name: losi-online
    image: ghcr.io/losi11/losi-online
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - LASTFM_API_KEY=${LASTFM_API_KEY}

networks:
  proxy:
    external: true
