services:
  losi-online:
    container_name: losi-online
    image: ghcr.io/losi11/losi-online@sha256:6bf186aaa5224c66c855a10ef859f312fa082396d7d1ca668017f4c2e16561bb
    restart: unless-stopped
    networks:
      - proxy
    env_file:
      - .env

networks:
  proxy:
    external: true
