services:
  lk-jwt-service:
    container_name: lk-jwt-service
    image: ghcr.io/element-hq/lk-jwt-service:0.7.0@sha256:e0c7cecfa74e2342a3e79d47e1d4ab4bd228fe05b1a4dc4ba7f807686b0c214b
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - LIVEKIT_URL=wss://livekit.matrix.ocd.beauty
      - LIVEKIT_KEY=${LIVEKIT_KEY}
      - LIVEKIT_SECRET=${LIVEKIT_SECRET}
      - LIVEKIT_FULL_ACCESS_HOMESERVERS=matrix.ocd.beauty

networks:
  proxy:
    external: true
