services:
  caddy:
    container_name: caddy
    image: caddy:2.11.4@sha256:13ba145cba2f3e28fa801994876e4c086d1b95d5aa2a520a734765ffb6b12017
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - data:/data
      - config:/config
      - ./etc/caddy/Caddyfile:/etc/caddy/Caddyfile
    extra_hosts:
      - host.docker.internal:host-gateway

networks:
  proxy:
    external: true

volumes:
  data:
  config:
