services:
  caddy:
    container_name: caddy
    image: caddy:2.11.4@sha256:df7f1c2fb114453b951de51a98efc010db1655a92c2e86be6706714e2417a78d
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - data:/data
      - config:/config
      - ./etc/caddy/Caddyfile:/etc/caddy/Caddyfile

networks:
  proxy:
    external: true

volumes:
  data:
  config:
